### ISSUE TITLE
Error occurs when Axe is about to break

### ISSUE THREAD

**Issue by allard1997** [Pozzoo/quickTreePlugin#1]
The error below shows in the console of the server when a player tries to chop a tree when the Axe runs out of durability.
To reproduce this, chop a tree with an Axe which has not enough or 1 durability. The player will not be able to chop down the tree and the error gets thrown into the console.

`[16:57:50 ERROR]: Could not pass event BlockBreakEvent to quickTree v1.3.0
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EquipmentSlot.ordinal()" because "slot" is null
        at net.minecraft.world.entity.LivingEntity.entityEventForEquipmentBreak(LivingEntity.java:4421) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.world.entity.LivingEntity.broadcastBreakEvent(LivingEntity.java:4451) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.world.item.ItemStack.lambda$hurtAndBreak$15(ItemStack.java:730) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:702) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:729) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.damageItemStack0(CraftLivingEntity.java:1147) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.damageItemStack(CraftLivingEntity.java:1136) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.inventory.ItemStack.damage(ItemStack.java:1043) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at quickTree-1.3.0.jar/com.github.pozzoo.quicktree.Listeners.BlockListener.onBlockBreak(BlockListener.java:28) ~[quickTree-1.3.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor135.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-71]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:git-Paper-71]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1845) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1517) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1494) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1417) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1244) ~[paper-1.20.6.jar:git-Paper-71]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-71]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by Pozzoo** [comment]
Hello! This issue seems to occur due to the paper/mojang changes on 1.20.5+ versions. Until I can fix the incompatibilities, I recommend running the plugin on a version older than 1.20.5!

**Comment by Pozzoo** [comment]
This has been fixed in the new 1.3.0-1.20.5 version
